version: '3.9'
services:
  posgres:
    container_name: postgres_rimay
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES="user_identity"
    ports:
      - '5432:5432'
